[package]
name = "hotaru"
version = "0.1.2"
description = "Markdown editor with Mermaid and Excalidraw previews"
authors = ["Hotaru"]
edition = "2024"

[lib]
name = "hotaru_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.9.3", features = [] }
tauri-plugin-dialog = "2.4.1"
