[package]
name = "koharu"
version = "1.1.0"
description = "Single-file text editor with optional Markdown preview"
authors = ["Daily AI Lab"]
edition = "2024"

[lib]
name = "koharu_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
atomicwrites = "0.4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.9.3", features = [] }
tauri-plugin-dialog = "2.4.1"

[dev-dependencies]
tempfile = "3"
